-- HR-style schema for plugin demos / screenshots.
-- Runs as SYS DBA on first container boot, so every object is HR.-qualified.

ALTER SESSION SET CONTAINER = FREEPDB1;

-- 1) DEPARTMENTS — small reference table (good for INDEX scan side of Explain Plan)
CREATE TABLE HR.DEPARTMENTS (
  DEPARTMENT_ID   NUMBER(4)     PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(30)  NOT NULL UNIQUE,
  LOCATION        VARCHAR2(40)
);
COMMENT ON TABLE  HR.DEPARTMENTS                IS '부서 마스터';
COMMENT ON COLUMN HR.DEPARTMENTS.DEPARTMENT_ID  IS '부서 코드';

-- 2) EMPLOYEES — main screenshot target (Columns + Data tab)
CREATE TABLE HR.EMPLOYEES (
  EMPLOYEE_ID    NUMBER(6)      PRIMARY KEY,
  FIRST_NAME     VARCHAR2(20),
  LAST_NAME      VARCHAR2(25)   NOT NULL,
  EMAIL          VARCHAR2(40)   NOT NULL UNIQUE,
  PHONE_NUMBER   VARCHAR2(20),
  HIRE_DATE      DATE           NOT NULL,
  JOB_ID         VARCHAR2(10)   NOT NULL,
  SALARY         NUMBER(8, 2),
  COMMISSION_PCT NUMBER(3, 2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)      REFERENCES HR.DEPARTMENTS(DEPARTMENT_ID),
  STATUS         VARCHAR2(10)   DEFAULT 'ACTIVE'  NOT NULL,
  CREATED_AT     TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CHK_EMP_SALARY  CHECK (SALARY > 0),
  CONSTRAINT CHK_EMP_STATUS  CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'TERMINATED'))
);

COMMENT ON TABLE  HR.EMPLOYEES                IS '직원 마스터';
COMMENT ON COLUMN HR.EMPLOYEES.EMPLOYEE_ID    IS '사원번호 (PK)';
COMMENT ON COLUMN HR.EMPLOYEES.FIRST_NAME     IS '이름';
COMMENT ON COLUMN HR.EMPLOYEES.LAST_NAME      IS '성';
COMMENT ON COLUMN HR.EMPLOYEES.EMAIL          IS '회사 이메일 (UQ)';
COMMENT ON COLUMN HR.EMPLOYEES.HIRE_DATE      IS '입사일';
COMMENT ON COLUMN HR.EMPLOYEES.JOB_ID         IS '직무 코드';
COMMENT ON COLUMN HR.EMPLOYEES.SALARY         IS '월 급여 (USD)';
COMMENT ON COLUMN HR.EMPLOYEES.COMMISSION_PCT IS '커미션 비율 (0~1)';
COMMENT ON COLUMN HR.EMPLOYEES.MANAGER_ID     IS '직속 상관 EMPLOYEE_ID';
COMMENT ON COLUMN HR.EMPLOYEES.DEPARTMENT_ID  IS '소속 부서 (FK → DEPARTMENTS)';
COMMENT ON COLUMN HR.EMPLOYEES.STATUS         IS '재직 상태 (ACTIVE / INACTIVE / TERMINATED)';
COMMENT ON COLUMN HR.EMPLOYEES.CREATED_AT     IS '레코드 생성 시각';

CREATE INDEX HR.IDX_EMP_DEPT ON HR.EMPLOYEES(DEPARTMENT_ID);
CREATE INDEX HR.IDX_EMP_NAME ON HR.EMPLOYEES(LAST_NAME, FIRST_NAME);
CREATE INDEX HR.IDX_EMP_HIRE ON HR.EMPLOYEES(HIRE_DATE);

-- 3) Trigger — for the Triggers tab screenshot
CREATE OR REPLACE TRIGGER HR.TRG_EMP_AUDIT
BEFORE UPDATE OF SALARY ON HR.EMPLOYEES
FOR EACH ROW
WHEN (NEW.SALARY <> OLD.SALARY)
BEGIN
  :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

-- 4) View — for the View dialog screenshot (DDL tab should show CREATE OR REPLACE VIEW)
CREATE OR REPLACE VIEW HR.EMP_DETAILS_V AS
SELECT
  e.EMPLOYEE_ID,
  e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
  e.EMAIL,
  e.JOB_ID,
  e.SALARY,
  e.HIRE_DATE,
  d.DEPARTMENT_NAME
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;
COMMENT ON TABLE HR.EMP_DETAILS_V IS '직원 + 부서 join 뷰';

-- 5) Sequence — for the Sequence dialog screenshot
CREATE SEQUENCE HR.EMPLOYEES_SEQ
  START WITH 2000
  INCREMENT BY 1
  CACHE 20
  NOCYCLE
  ORDER;

-- 6) Synonym — for the Synonym dialog screenshot
CREATE OR REPLACE SYNONYM HR.EMP FOR HR.EMPLOYEES;
