-- PL/SQL Package for the Package-dialog screenshot.
-- Has Spec + Body + multiple routines so the Routines tab shows several rows.

ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE OR REPLACE PACKAGE HR.HR_UTIL AS
  -- 직원 수 (활성만)
  FUNCTION  ACTIVE_COUNT      RETURN NUMBER;

  -- 평균 급여
  FUNCTION  AVG_SALARY        RETURN NUMBER;

  -- 부서별 직원 수 출력
  PROCEDURE PRINT_DEPT_SUMMARY;

  -- 사원 ID로 전체 이름 (overload demo)
  FUNCTION  FULL_NAME(p_id IN NUMBER) RETURN VARCHAR2;
  FUNCTION  FULL_NAME(p_email IN VARCHAR2) RETURN VARCHAR2;
END HR_UTIL;
/

CREATE OR REPLACE PACKAGE BODY HR.HR_UTIL AS

  FUNCTION ACTIVE_COUNT RETURN NUMBER IS
    l_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_cnt
    FROM HR.EMPLOYEES
    WHERE STATUS = 'ACTIVE';
    RETURN l_cnt;
  END ACTIVE_COUNT;

  FUNCTION AVG_SALARY RETURN NUMBER IS
    l_avg NUMBER;
  BEGIN
    SELECT AVG(SALARY) INTO l_avg
    FROM HR.EMPLOYEES
    WHERE STATUS = 'ACTIVE';
    RETURN ROUND(l_avg, 2);
  END AVG_SALARY;

  PROCEDURE PRINT_DEPT_SUMMARY IS
  BEGIN
    FOR rec IN (
      SELECT d.DEPARTMENT_NAME, COUNT(e.EMPLOYEE_ID) AS HEADCOUNT
      FROM   HR.DEPARTMENTS d
      LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
      GROUP BY d.DEPARTMENT_NAME
      ORDER BY HEADCOUNT DESC
    ) LOOP
      DBMS_OUTPUT.PUT_LINE(RPAD(rec.DEPARTMENT_NAME, 30) || rec.HEADCOUNT);
    END LOOP;
  END PRINT_DEPT_SUMMARY;

  FUNCTION FULL_NAME(p_id IN NUMBER) RETURN VARCHAR2 IS
    l_name VARCHAR2(60);
  BEGIN
    SELECT FIRST_NAME || ' ' || LAST_NAME
      INTO l_name
      FROM HR.EMPLOYEES
     WHERE EMPLOYEE_ID = p_id;
    RETURN l_name;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
  END FULL_NAME;

  FUNCTION FULL_NAME(p_email IN VARCHAR2) RETURN VARCHAR2 IS
    l_name VARCHAR2(60);
  BEGIN
    SELECT FIRST_NAME || ' ' || LAST_NAME
      INTO l_name
      FROM HR.EMPLOYEES
     WHERE EMAIL = p_email;
    RETURN l_name;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
  END FULL_NAME;

END HR_UTIL;
/
